### ISSUE TITLE
I18n Spanish: Patient - Data Entry

### ISSUE THREAD

**Issue by lomky** [DCAFEngineering/dcaf_case_management#1581]
## What are we trying to do?

This ticket is part of the DARIA translation effort. The goal is to implement all our text in both English and Spanish through the i18n* process. 

This ticket is for the Patient Data Entry view.  
Code link:  
app/views/patients/data_entry.html.erb

The current English text should be moved to `config/locales/en.yml`,   
and new Spanish text should be added to `config/locales/es.yml`.

**Google translate is perfectly acceptable!**  
PRs will be reviewed by a fluent CM to correct any weirdness.

For this ticket, consider reusing keys defined for the main Patient object!

### Steps

For each view  
 - find each instance of displayed text on the view
   `<%= f.date_field :appointment_date, label: 'Appointment date', autocomplete: 'off', help: "Approx gestation at appt: #{patient.last_menstrual_period_at_appt}" %>`
 - replace it with a call to i18n `t` function with a unique identifier based on the file path & field
   `<%= f.date_field :appointment_date, label: t('patient.dashboard.appt_date'), autocomplete: 'off', help: t('patient.dashboard.approx_gestation', gest: patient.last_menstrual_period_at_appt) %>`
 - add a config entry for each language with that identifier as the key, and the language line as the value.
   `en.yml`:
   ```
   patient:
     dashboard:
       approx_gestation: 'Approx gestation at appt: %{gest}'
       appt_date: Appointment date
    ```  
    `es.yml`:
    ```
    patient:
      dashboard:
        approx_gestation: 'Aprox la gestación en la cita: %{gest}'
        appt_date: Día de la cita
    ```

### Completed View Example

For an example of a completed view translation, see [the footer view i18n PR](https://github.com/DCAFEngineering/dcaf_case_management/pull/1547/files).

### Formatting in the YAML files

Each view should have a it's own section. If you see the same key being used across Some commonly used values can go under a shared secton. `app/views/patients/_patient_dashboard.html.erb` keys go under `patient:` -> `dashboard:`.

**For this particular view, you should consider reusing existing fields under patient!**

### Finalizing with i18n-tasks

After you finish all the keys, you should run the i18n checker before committing! This sorts the keys in a standard way and checks for missing keys.

`i18n-tasks normalize`
`i18n-tasks health` - address any issues this highlights!

[More info on using i18n-tasks](https://github.com/glebm/i18n-tasks)

\* 'i18n' is shorthand for 'Internationalization'. [More info on i18n in Rails](https://guides.rubyonrails.org/i18n.html)

Part of #1382
