### ISSUE TITLE
Translate Practical Support module

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1722]
* **What are we trying to do?**
This ticket is part of the DARIA translation effort. We are trying to implement our text in both English and Spanish thru the i18n process.

This ticket is for the practical support module.
Code link: 
app/views/views/practical_supports/*
app/controllers/practical_supports_controller.rb (flash messages)

In addition, there's an additional menu item to translate, `practical_support`. Add that in en.yml and es.yml under `patient.menu`.
We also need to translate the dropdown options, which should be under `patient.helper.practical_support`. Those are located in app/helpers/patients_helper.rb.

* **How could we solve this issue? (Not knowing is okay!)**
### Steps

For each view  
 - find each instance of displayed text on the view
   `<%= f.date_field :appointment_date, label: 'Appointment date', autocomplete: 'off', help: "Approx gestation at appt: #{patient.last_menstrual_period_at_appt}" %>`
 - replace it with a call to i18n `t` function with a unique identifier based on the file path & field
   `<%= f.date_field :appointment_date, label: t('patient.dashboard.appt_date'), autocomplete: 'off', help: t('patient.dashboard.approx_gestation', gest: patient.last_menstrual_period_at_appt) %>`
 - add a config entry for each language with that identifier as the key, and the language line as the value.
   `en.yml`:
   ```
   patient:
     dashboard:
       approx_gestation: 'Approx gestation at appt: %{gest}'
       appt_date: Appointment date
    ```  
    `es.yml`:
    ```
    patient:
      dashboard:
        approx_gestation: 'Aprox la gestación en la cita: %{gest}'
        appt_date: Día de la cita
    ```

### Completed View Example

For an example of a completed view translation, see [the footer view i18n PR](https://github.com/DCAFEngineering/dcaf_case_management/pull/1547/files).

### Formatting in the YAML files

Each view should have a it's own section. If you see the same key being used across Some commonly used values can go under a shared secton. `app/views/patients/_patient_dashboard.html.erb` keys go under `patient:` -> `dashboard:`.

### Finalizing with i18n-tasks

After you finish all the keys, you should run the i18n checker before committing! This sorts the keys in a standard way and checks for missing keys.

`i18n-tasks normalize`
`i18n-tasks health` - address any issues this highlights!

[More info on using i18n-tasks](https://github.com/glebm/i18n-tasks)

\* 'i18n' is shorthand for 'Internationalization'. [More info on i18n in Rails](https://guides.rubyonrails.org/i18n.html)

stems from #1493
